// !!! This is a file automatically generated by hipify!!!
#ifndef THC_INC
#define THC_INC

#include <THH/THHGeneral.h>
#include <ATen/hip/impl/HIPCachingAllocatorMasqueradingAsCUDA.h>
#include <THH/THHSleep.h>
#include <THH/THHStorage.h>

#include <THH/THHTensor.h>

#endif
