// !!! This is a file automatically generated by hipify!!!
#ifndef THC_STORAGE_INC
#define THC_STORAGE_INC

#include <TH/THStorageFunctions.h>
#include <THH/THHGeneral.h>

#define THCStorage_(NAME) TH_CONCAT_4(TH,CReal,Storage_,NAME)

#include <THH/generic/THHStorage.h>
#include <THH/THHGenerateByteType.h>

#endif
