// !!! This is a file automatically generated by hipify!!!
#include <THH/THHGeneral.h>
#include <THH/THHTensor.hpp>

#include <new>

#include <THH/generic/THHTensor.cpp>
#include <THH/THHGenerateByteType.h>

void THCTensor_setStorage(THCState *state, THCTensor *self, THCStorage *storage_, ptrdiff_t storageOffset_, at::IntArrayRef size_, at::IntArrayRef stride_)
{
  c10::raw::intrusive_ptr::incref(storage_);
  THTensor_wrap(self).set_(at::Storage(c10::intrusive_ptr<at::StorageImpl>::reclaim(storage_)),
                           storageOffset_, size_, stride_);
}
